version: '3.6'
services:
  backend:
    build: ./
    restart: always
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/ar_amenagement

  mongo:
    image: mongo
    volumes:
      - db_data:/data/db
    expose:
      - "27017"

#  swagger:
#    image: swaggerapi/swagger-ui
#    depends_on:
#      - backend
#    ports:
#      - "80:8080"

#  frontend:
#    build: ../Frontend-Unity
#    ports:
#      - "4200:4200"

volumes:
  db_data:
